#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xt?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 3333

wx:
  open:
    config:
      # 微信开放平台创建的网站应用的appid
      appid: wx80433f71827c6b57
      # 微信开放平台创建的网站应用的appsecret
      secret: b9a3a12f64307476a2135432f1b46704
      # 登录作用域
      scope: snsapi_login
      # 回调认证状态，用于认证回调的有效性
      csrfkey: catdog
      # 微信开放平台创建的网站 设置的授权回调域
      redirectUrl: http://www.mszlu.com/api/sso/login/wxLoginCallBack