#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xt?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 3333
  redis:
    host: localhost
    port: 6379

wx:
  open:
    config:
      # 微信开放平台创建的网站应用的appid
      appid: wx********27c6b57
      # 微信开放平台创建的网站应用的appsecret
      secret: b9a3a***********2135432f1b46704
      # 登录作用域
      scope: s*******gin
      # 回调认证状态，用于认证回调的有效性
      csrfkey: a***dog
      # 微信开放平台创建的网站 设置的授权回调域
      redirectUrl: http://www.***********inCallBack
